name: Java CI with Maven

on:
  push:
    branches: [ development, testing, acceptance ]
  pull_request:
    branches: [ development, testing, acceptance ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠️ Build with Maven
        run: mvn clean install

      - name:  Run Tests
        run: mvn test

      - name:  Generate JaCoCo Report
        run: mvn verify
